source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def common_pods
  pod 'ActionCableClient', :path => '../'
end

target 'ActionCableClient_Example' do
    common_pods
    pod 'SnapKit'
    pod 'SwiftyJSON'
end

target 'ActionCableClient_Tests' do
  common_pods
  pod 'Quick', '~> 0.9.1'
  pod 'Nimble', '3.0.0'
end
